Update fetchjenkins.yml

diff --git a/.github/workflows/fetchjenkins.yml b/.github/workflows/fetchjenkins.yml
--- a/.github/workflows/fetchjenkins.yml
+++ b/.github/workflows/fetchjenkins.yml
@@ -14,9 +14,9 @@ jobs:
           # Replace the URL with your actual Jenkins API URL
           echo "Jenkins Credentials: ${{ secrets.JENKINS_CREDENTIALS }}"
           JENKINS_CREDENTIALS="${{ secrets.JENKINS_CREDENTIALS }}"
-          echo "curl -u '$JENKINS_CREDENTIALS' -s http://localhost:8080/job/matt-wash-projects/job/main/lastSuccessfulBuild/testReport/api/json"
-          curl -u "$JENKINS_CREDENTIALS" -s http://localhost:8080/job/matt-wash-projects/job/main/lastSuccessfulBuild/testReport/api/json || echo "Curl Error: $?"
-          # API_RESPONSE=$(curl -u ${{ secrets.JENKINS_CREDENTIALS }} -s http://localhost:8080/job/matt-wash-projects/job/main/lastSuccessfulBuild/testReport/api/json)
+          echo "curl -u '$JENKINS_CREDENTIALS' -s http://127.0.0.1:8080/job/matt-wash-projects/job/main/lastSuccessfulBuild/testReport/api/json"
+          curl -u "$JENKINS_CREDENTIALS" -s http://127.0.0.1:8080/job/matt-wash-projects/job/main/lastSuccessfulBuild/testReport/api/json || echo "Curl Error: $?"
+          # API_RESPONSE=$(curl -u ${{ secrets.JENKINS_CREDENTIALS }} -s http://127.0.0.1:8080/job/matt-wash-projects/job/main/lastSuccessfulBuild/testReport/api/json)
 
           echo "$API_RESPONSE"
           # Extract passCount, skipCount, failCount, and store them as environment variables
